### ISSUE TITLE
URL links to survey scam

### ISSUE THREAD

**Issue by paulmasson** [rreusser/principle-of-least-action-demo#1]
@rreusser this link leads to a survey scam of some sort:

http://rickyreusser.com/principle-of-least-action-demo/

Have you been hacked or is this deliberate?

**Comment by rreusser** [comment]
Thanks for letting me know! I've removed it. I let my personal domain expire a couple years ago now since github pages was so much easier to maintain, but I know I did miss a link or two. Sorry about that!

**Comment by paulmasson** [comment]
A search on GitHub under your user name for "rickyreusser com" returns over a hundred files. Some of these merely contain references to your Twitter feed, but the bulk point to your old website. You might want to fix some more of these: I certainly wouldn't want my name or work associated with a scam site. Any idea who owns it now?

**Comment by rreusser** [comment]
Okay, apologies that was a pretty half-hearted effort. Thanks for pushing me on this. It took a few hours, but I've archived about half of my repositories, maybe deleted a quarter, submitted some PRs against other people's sites, and have removed my domain from as many of my own repos as I can find–at least until I wait for github search to reindex.

Apologies for my continued laziness and for breaking my small corner of the web. I'm trying to do better about consolidating work and, frankly, putting a bit of mathematical artwork (with source) into the wild but as little actual software as I can. It's just too hard to maintain. 😞
